apiVersion: v1
kind: Namespace
metadata:
  name: ci-deploy

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ci-deployer
  namespace: ci-deploy

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ci-deployer-role
  namespace: ci-deploy
rules:
  - apiGroups: ["", "apps", "extensions"]
    resources:
      - pods
      - pods/log
      - services
      - endpoints
      - configmaps
      - secrets
      - replicationcontrollers
      - replicasets
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ci-deployer-binding
  namespace: ci-deploy
subjects:
  - kind: ServiceAccount
    name: ci-deployer
    namespace: ci-deploy
roleRef:
  kind: ClusterRole
  name: ci-deployer-role
  apiGroup: rbac.authorization.k8s.io