name: Build and Push Docker Image
on: 

    push:
    pull_request:
    workflow_run:
        workflows: ["CI"]
        types:
            - completed
    workflow_dispatch:

permissions:
    contents: write
    id-token: write
    packages: write

jobs:
    build:
        name: Build and Push Docker Image
        runs-on: ubuntu-latest
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/test' }}
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            IMAGE: test
            REPO_LOWER: test
            CACHE_REF: test
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Login to Docker Registry
              uses: docker/login-action@v2
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ env.GITHUB_TOKEN }}

            - name: Prepare image names
              shell: bash
              run: |
                REPO="${{ github.repository }}"                      
                REPO_LOWER=$(echo "$REPO" | tr '[:upper:]' '[:lower:]' | tr '_' '-')
                IMAGE="ghcr.io/${REPO_LOWER}/demo-app:ci-${{ github.sha }}"
                CACHE_REF="ghcr.io/${REPO_LOWER}/demo-app:cache"
                echo "REPO_LOWER=$REPO_LOWER" >> $GITHUB_ENV
                echo "IMAGE=$IMAGE" >> $GITHUB_ENV
                echo "CACHE_REF=$CACHE_REF" >> $GITHUB_ENV
                echo "Prepared IMAGE=$IMAGE"

            - name: Show IMAGE (debug)
              run: |
                echo "IMAGE=$IMAGE"
                docker --version

            - name: Build and Push Docker Image
              uses: docker/build-push-action@v4
              with:
                context: ./src/demo_app
                file: ./src/demo_app/Dockerfile
                push: true                          
                tags: |
                    ${{ env.IMAGE }}
                    ghcr.io/${{ env.REPO_LOWER }}/demo-app:latest
                    cache-from: |
                    type=registry,ref=${{ env.CACHE_REF }}
                    cache-to: type=inline
                
            - name: Upload image metadata
              if: ${{ github.action == 'true' }}
              uses: actions/upload-artifact@v4
              with:
                name: image-info
                path: |
                    image-name.txt