name: Infra Deploy

on:
    repository_dispatch:
        types: [infra-deploy]

jobs:
    build:
        name: Terraform Apply
        runs-on: ubuntu-latest
        environment: production
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: latest
                
            - name: Terraform Init
              working-directory: ./infra/terraform
              run: terraform init -input=false

            - name: Terraform Apply
              working-directory: ./infra/terraform
              run: terraform apply -auto-approve -input=false -var-file=envs/dev.tfvars