name: Security Scan
on: 
    push:
    pull_request:
    workflow_run:
        workflows: ["Build and Push Docker Image"]
        types:
            - completed
            
permissions:
    contents: read
    packages: read

jobs: 
    trivy-scan:
        runs-on: ubuntu-latest
        env:
            IMAGE: test
        if: |
            ${{ github.event.workflow_run.conclusion == 'success' }}
            ${{ github.action == 'true' }}
        steps:
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Prepare IMAGE for scan
              run: |
                REPO="${{ github.repository }}"
                REPO_LOWER=$(echo "$REPO" | tr '[:upper:]' '[:lower:]' | tr '_' '-')
                echo "IMAGE=ghcr.io/${REPO_LOWER}/demo-app:ci-${{ github.sha }}" >> $GITHUB_ENV
                  
            - name: Pull Docker Image
              run: |
                echo "IMAGE=${{ env.IMAGE }}"
                docker pull "${{ env.IMAGE }}"
                

            - name: Run Trivy Scan
              uses: aquasecurity/trivy-action@master
              with:
                    image-ref: ${{ env.IMAGE }}
                    format: 'sarif'
                    output: 'trivy-report.sarif'
                    exit-code: '0'

            - name: Install jq
              run: |
                  sudo apt-get install -y jq

            - name: Filter unsupported run results from SARIF
              run: |
                jq '.runs |= map(select(.tool.driver.name | test("aws|k8s"; "i") | not))' trivy-report.sarif > trivy-report-filtered.sarif
                jq -r '.runs[].tool.driver.name' trivy-report-filtered.sarif || true

            - name: Convert filtered SARIF to HTML
              run: |
                  trivy convert --format template --template "@contrib/html.tpl" --output trivy-report.html trivy-report-filtered.sarif
                  
            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./ 
                  publish_branch: gh-pages
                  force_orphan: true
                  keep_files: false
                  allow_empty_commit: false

            - name: Upload SARIF artifact
              uses: actions/upload-artifact@v4
              with:
                name: trivy-sarif
                path: trivy-report.sarif
